### ISSUE TITLE
Api key not valid

### ISSUE THREAD

**Issue by gigi81** [TestableIO/System.IO.Abstractions.Extensions#65]
https://github.com/TestableIO/System.IO.Abstractions.Extensions/actions/runs/8055278445/job/22001898774

Hi @fgreinacher can you please check the nuget API key in the project secrets as the publish is currently failing? thanks

**Comment by fgreinacher** [comment]
@gigi81 I [have stepped out of this project](https://github.com/TestableIO/System.IO.Abstractions/issues/1080), so I cannot help anymore, sorry!

@vbreuss Could you have a look?

**Comment by vbreuss** [comment]
I will have a look in the next couple of days.

**Comment by vbreuss** [comment]
@gigi81
I updated the API Key and re-ran the failed build. The deploy-step was now successful.

**Comment by gigi81** [comment]
@vbreuss thank you!
